# Generated by Django 5.0.2 on 2024-02-15 01:39

import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=26, prefix='map', primary_key=True, serialize=False, unique=True)),
                ('game_item_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('localizedname', models.CharField(max_length=255)),
                ('authors', models.CharField(max_length=255)),
            ],
        ),
    ]
