# Generated by Django 5.0.2 on 2024-02-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='authors',
            field=models.CharField(blank=True, help_text='The authors of the map.', max_length=255),
        ),
        migrations.AlterField(
            model_name='map',
            name='localizedname',
            field=models.CharField(help_text='The localized name of the map.', max_length=255),
        ),
    ]
