services:
  app:
    build: ./
    container_name: tf2_api_app
    # command: gunicorn tf2_api.wsgi:application --bind 0.0.0.0:8000 --reload
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8001:8000"
    volumes:
      - ./:/app/
    env_file:
      - .env
    depends_on:
      db:
        condition: service_started
    restart: always
    networks:
      - tf2-api-network
  db:
    image: postgres:15.1
    container_name: tf2_api_db
    environment:
      - POSTGRES_DB=tf2_db
      - POSTGRES_USER=tf2_user
      - POSTGRES_PASSWORD=tf2_password
    restart: always
    ports:
      - "5434:5432"
    networks:
      - tf2-api-network
    healthcheck:
      test: "exit 0"

networks:
  tf2-api-network:
    name: tf2-api-network
    external: true