# Generated by Django 5.0.2 on 2024-02-18 18:12

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('qualities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prefab',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=29, prefix='prefab', primary_key=True, serialize=False, unique=True)),
                ('game_item_id', models.CharField(max_length=255)),
                ('item_class', models.CharField(blank=True, max_length=255, null=True)),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_type_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('item_slot', models.CharField(blank=True, max_length=255, null=True)),
                ('craft_class', models.CharField(blank=True, max_length=255, null=True)),
                ('craft_material_type', models.CharField(blank=True, max_length=255, null=True)),
                ('image_inventory', models.CharField(blank=True, max_length=255, null=True)),
                ('equip_region', models.CharField(blank=True, max_length=255, null=True)),
                ('mouse_pressed_sound', models.CharField(blank=True, max_length=255, null=True)),
                ('drop_sound', models.CharField(blank=True, max_length=255, null=True)),
                ('tags_is_cosmetic', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_is_taunt_item', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_deal_damage', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_deal_gib_damage', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_be_equipped_by_soldier_or_demo', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_deal_posthumous_damage', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_deal_critical_damage', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_deal_long_distance_damage', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_headshot', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_deal_mvm_penetration_damage', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_heal_allies', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_destroy_sappers', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_reflect_projectiles', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_extinguish', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_is_flamethrower', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_apply_soldier_buff', models.BooleanField(blank=True, default=False, null=True)),
                ('tags_can_deal_taunt_damage', models.BooleanField(blank=True, default=False, null=True)),
                ('public_prefab', models.BooleanField(blank=True, default=False, null=True)),
                ('show_in_armory', models.BooleanField(blank=True, default=False, null=True)),
                ('used_by_scout', models.BooleanField(blank=True, default=False, null=True)),
                ('used_by_sniper', models.BooleanField(blank=True, default=False, null=True)),
                ('used_by_soldier', models.BooleanField(blank=True, default=False, null=True)),
                ('used_by_demoman', models.BooleanField(blank=True, default=False, null=True)),
                ('used_by_medic', models.BooleanField(blank=True, default=False, null=True)),
                ('used_by_heavy', models.BooleanField(blank=True, default=False, null=True)),
                ('used_by_spy', models.BooleanField(blank=True, default=False, null=True)),
                ('used_by_pyro', models.BooleanField(blank=True, default=False, null=True)),
                ('used_by_engineer', models.BooleanField(blank=True, default=False, null=True)),
                ('min_ilevel', models.IntegerField(blank=True, null=True)),
                ('max_ilevel', models.IntegerField(blank=True, null=True)),
                ('item_quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qualities.quality')),
                ('prefabs', models.ManyToManyField(blank=True, to='prefabs.prefab')),
            ],
        ),
    ]
