# Generated by Django 5.0.2 on 2024-02-15 01:33

import django.db.models.deletion
import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rarity',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=29, prefix='rarity', primary_key=True, serialize=False, unique=True)),
                ('game_item_id', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('loc_key', models.CharField(max_length=255)),
                ('drop_sound', models.CharField(max_length=255)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colors.color')),
                ('next_rarity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rarites.rarity')),
            ],
        ),
    ]
