# Generated by Django 5.0.2 on 2024-02-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rarites', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rarity',
            old_name='drop_sound',
            new_name='loc_key_weapon',
        ),
    ]
