# Generated by Django 5.0.2 on 2024-02-16 15:42

import prefix_id.field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfiles',
            name='id',
            field=prefix_id.field.PrefixIDField(editable=False, max_length=27, prefix='file', primary_key=True, serialize=False, unique=True),
        ),
    ]
