# Generated by Django 5.0.2 on 2024-02-16 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0002_alter_trackfiles_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrackFiles',
            new_name='TrackFile',
        ),
    ]
