# Generated by Django 5.0.2 on 2024-02-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_rename_trackfiles_trackfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfile',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
