# Generated by Django 5.0.2 on 2024-02-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0004_alter_trackfile_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackfile',
            name='last_modified',
            field=models.DateTimeField(blank=True),
        ),
    ]
