# Generated by Django 5.0.2 on 2024-02-14 19:08

import prefix_id.field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', prefix_id.field.PrefixIDField(editable=False, max_length=28, prefix='color', primary_key=True, serialize=False, unique=True)),
                ('game_item_id', models.CharField(max_length=255)),
                ('color_name', models.CharField(max_length=255)),
                ('color_hex', models.CharField(max_length=7)),
            ],
        ),
    ]
